### ISSUE TITLE
BMS enters config_assert while loop sometimes on Startup or while communicating through serial

### ISSUE THREAD

**Issue by Goku5036** [foxBMS/foxbms-1#13]
Hello, i am using foxbms in eclipse with the GNU toolchain environment (GNU 10) . My setup communicates through RS485. The user can communicate with the system though serial port and use certain pre-defined commands to get the status of the system. However, sometimes during this process it stops responding completely. On debugging it is seen that it enters the configassert while loop. This sometimes also occur after startup of the system. 

I am attaching the debug call stack with the issue, please do let me know what can be done.  

![Screenshot (21)](https://user-images.githubusercontent.com/79309024/124612255-783f8980-de72-11eb-8f17-c43cfecd53e1.png)

**Comment by foxBMS** [comment]
Dear @Goku5036 ,

foxBMS 1 is no longer supported or updated.

The further development of the foxBMS project is done in the second generation of foxBMS - foxBMS 2.
foxBMS 2 is also available on GitHub at <https://github.com/foxBMS/foxbms-2>.

Best regards,
The foxBMS Team
