### ISSUE TITLE
foxBMS PCBA

### ISSUE THREAD

**Issue by richard198203** [foxBMS/foxbms-1#14]
If you need the foxBMS PCBA, please click on the link: https://www.youtube.com/watch?v=gXM_qo0uZdY

**Comment by foxBMS** [comment]
Dear @richard198203,

foxBMS 1 is no longer supported or updated.

The further development of the foxBMS project is done in the second generation of foxBMS - foxBMS 2.
foxBMS 2 is also available on GitHub at <https://github.com/foxBMS/foxbms-2>.

Best regards,
The foxBMS Team
