### ISSUE TITLE
Message: CAN0_MSG_SOP Feature Support

### ISSUE THREAD

**Issue by bmaxon** [foxBMS/foxbms-1#6]
Is there any timeline for adding support to this CAN message? It would be great to record the `CAN0_SIG_MaxDischargePower` for calculating battery drain rate

**Comment by foxBMS** [comment]
Dear @bmaxon ,

foxBMS 1 is no longer supported or updated.

The further development of the foxBMS project is done in the second generation of foxBMS - foxBMS 2.
foxBMS 2 is also available on GitHub at <https://github.com/foxBMS/foxbms-2>.

Best regards,
The foxBMS Team
